### PR TITLE
Handle `@APIResponseSchema` without generated content

### LINKED ISSUE #1026: NPE when @Produces is missing
### Code to follow for reproducing the issue

1. `ResponseReader.addApiReponseSchemaFromAnnotation`:
```
APIResponse response = ResponseReader.readResponseSchema(context, annotation);

if (response.getDescription() == null) {
    response.setDescription(getReasonPhrase(status));
}
```
2. `ResponseReader.readResponseSchema`:

```
if (annotation == null || CurrentScannerInfo.getCurrentProduces() == null) {
    // Only generate the APIResponse if the endpoint declares an @Produces media type
    return null;
}
```

When `@Produces` is missing on the scanned method, it will raise the most known java exception: `NPE` 

Also, we are using @APIResponseSchema to specify the schema for a certain method, because we work with `javax.ws.rs.core.Response`. Maybe an enhancement is to prioritize it before returning null in method no 2 from above.

### Bonus maybe irelevent bug
Rename addApi**Reponse**SchemaFromAnnotation -> addApi**Response**SchemaFromAnnotation

### Env
* `quarkus` - 2.6.1
* `quarkus-smallrye-openapi1` - 2.6.1

### PR DESCRIPTION
**Pull request by MikeEdgar**
Fixes #1026

### CODE REVIEW

File: core/src/main/java/io/smallrye/openapi/runtime/io/response/ResponseReader.java [hunk 1]
```diff
@@ -179,25 +181,31 @@ public static APIResponse readResponse(final AnnotationScannerContext context,
...
 
         APIResponseImpl response = new APIResponseImpl();
         response.setDescription(JandexUtil.value(annotation, ResponseConstant.PROP_RESPONSE_DESCRIPTION));
-        response.setContent(content);
         response.setResponseCode(JandexUtil.value(annotation, ResponseConstant.PROP_RESPONSE_CODE));
+
+        Type responseType = JandexUtil.value(annotation, ResponseConstant.PROP_VALUE);
+
+        if (CurrentScannerInfo.getCurrentProduces() != null && !TypeUtil.isVoid(responseType)) {
+            // Only generate the content if the endpoint declares an @Produces media type
```
Comment (MikeEdgar) [inline core/src/main/java/io/smallrye/openapi/runtime/io/response/ResponseReader.java:196]: Checking `void` doesn't really enable anything that couldn't be done with `@APIResponse`, but reduces surprises if `void.class` is given as the `value` for `@APIResponseSchema` and there *is* `@Produces` annotation.

**Review by phillip-kruger — APPROVED** [review]
LGTM
